# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 499de26589cae48bc020a21cc8ab0b772770fbe1e223efa0c762daa81f8cb39c3e9f955d430955d71f5d05f60bcf5921768e82715932e2d5304d857827d24b73

test:
  domain_name: example.com 
  secret_key_base: 93f5898dcdabba4c4dc9d45ba867f6c653a71109f50b53781c23b53cbd7d97a093ce7a63da29456764ea3fc495b9fcff5d858e4c8a8ce8f846f6897e11abaed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: administrador
  admin_email: siave@seed.ap.gov.br
  admin_password: 123123123
  domain_name: siged.seed.ap.gov.br
  secret_key_base: 499de26589cae48bc020a21cc8ab0b772770fbe1e223efa0c762daa81f8cb39c3e9f955d430955d71f5d05f60bcf5921768e82715932e2d5304d857827d24b73
